In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/main/hiring.csv")
df.head()

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [3]:
df.shape

(8, 4)

In [4]:
df.isna().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [5]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [6]:
# experience

df['experience'].fillna(0, inplace=True)

In [7]:
df.isna().sum()

experience         0
test_score         1
interview_score    0
salary             0
dtype: int64

In [8]:
df.test_score.mean()

7.857142857142857

In [9]:
df.test_score.fillna(df.test_score.mean(), inplace=True)
df.isna().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

# Dataset is clean now.

In [10]:
df

experience  test_score  interview_score  salary
0          0    8.000000                9   50000
1          0    8.000000                6   45000
2       five    6.000000                7   60000
3        two   10.000000               10   65000
4      seven    9.000000                6   70000
5      three    7.000000               10   62000
6        ten    7.857143                7   72000
7     eleven    7.000000                8   80000

In [11]:
X = df.iloc[ : , :-1 ]
X

experience  test_score  interview_score
0          0    8.000000                9
1          0    8.000000                6
2       five    6.000000                7
3        two   10.000000               10
4      seven    9.000000                6
5      three    7.000000               10
6        ten    7.857143                7
7     eleven    7.000000                8

In [12]:
X.shape

(8, 3)

In [13]:
# Convert text in the cols to integer values

def conv(x):
    dict = {
        'two' : 2,
        'three' : 3,
        'five' : 5,
        'seven' : 7,
        'ten' : 10,
        'eleven' : 11,
        0 : 0
    }
    return dict[x]

In [14]:
X['experience'] = X['experience'].apply(lambda x: conv(x))

In [15]:
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [16]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   experience       8 non-null      int64  
 1   test_score       8 non-null      float64
 2   interview_score  8 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 320.0 bytes


## X is ready.

In [17]:
y = df.iloc[ : , -1 ]
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [18]:
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

I am not going to do traintestsplit in the dataset as it very small.

However, you all are encoutaged to it later as a part ofpractice.

In [19]:
# Modeling

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [20]:
# Fit the model
lr.fit(X, y)

LinearRegression()

In [21]:
lr

LinearRegression()

In [22]:
# Prediction Phase

y_pred = lr.predict(X)
y_pred

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [23]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [24]:
from sklearn.metrics import r2_score
r2_score(y_pred, y)

0.9626511210293308

In [25]:
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [26]:
lr.predict([[3,9,7]])

array([58315.5019167])

In [27]:
lr.predict([[10,10,10]])

array([86612.80419155])

In [28]:
lr.predict([[10,2,3]])

array([55930.47274854])

# Model Deployment

In [29]:
# here, we will save the "lr" model to local disk

import pickle

pickle.dump(lr, open('Shreyas_Model.pkl','wb'))
# Dump this model by name 'Shreyas_Model.pkl' in the systems disk and while
# doing this, write this file using "write bytes" mode.

# End of our NB

# Client's Side

In [31]:
# Lets try to load the same model by reading it from the systems local disk
# and using it for prediction

model2 = pickle.load(open("Shreyas_Model.pkl","rb"))

In [32]:
model2

LinearRegression()

In [33]:
model2.predict([[3,9,7]])

array([58315.5019167])

In [34]:
model2.predict([[10,10,10]])

array([86612.80419155])

In [35]:
model2.predict([[10,2,3]])

array([55930.47274854])

# Happy Learning